sudo: required
language: python

python:
  - "2.7"

env:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/Ehtaga/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}
  - sudo pip install num2words
  - git clone --depth=1 https://github.com/OCA/account-fiscal-rules.git /tmp/fiscal-rules -b ${VERSION}

script:
  - travis_run_tests ${VERSION} /tmp/fiscal-rules

after_success:
  coveralls
