sudo: required
language: python

python:
  - "2.7"

env:
  global:
    - VERSION="8.0" LINT_CHECK="0" TESTS="0" TRANSIFEX="0"
    - TRANSIFEX_USER='test_transifex_oca'
    - secure: PjP88tPSwimBv4tsgn3UcQAD1heK/wcuSaSfhi2xUt/jSrOaTmWzjaW2gH/eKM1ilxPXwlPGyAIShJ2JJdBiA97hQufOeiqxdkWDctnNVVEDx2Tk0BiG3PPYyhXPgUZ+FNOnjZFF3pNWvzXTQaB0Nvz8plqp93Ov/DEyhrCxHDs=

  matrix:
    - LINT_CHECK="1"
    - TRANSIFEX="1"
    - TESTS="1" ODOO_REPO="odoo/odoo"
    - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/Ehtaga/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}
  - sudo pip install num2words
  - git clone --depth=1 https://github.com/OCA/account-fiscal-rules.git /tmp/fiscal-rules -b ${VERSION}

script:
  - travis_run_tests ${VERSION} /tmp/fiscal-rules

after_success:
  coveralls
